name: pre-release
on:
  push:
    branches: [ master ]
    paths-ignore: [ '*.md' ]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }}
    steps:
      - name: Get Current Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYYMMDDHHmmss'
  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Build
        run: |
          bash build.sh
          sha1sum packages/mesagisto.mirai2.jar > packages/mesagisto.mirai2.jar.sha1
        env:
          VERSION: beta-${{needs.prepare.outputs.time}}

      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: beta-${{needs.prepare.outputs.time}}
          prerelease: true
          title: "Unstable PreRelease/不稳定预发行版"
          files: |
            packages/*
            LICENSE

      - name: Delete older releases and tags
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tag_pattern: beta
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: startsWith(github.repository, 'Mesagisto')
    steps:

      - name: Clone Mirai-Repo
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_HOST: "github.com"
        run: |
          git config --global user.name "MesagistoBot"
          git config --global user.email "bot@mesagisto.org"
          gh auth setup-git
          gh repo delete MesagistoBot/mirai-repo-mirror --confirm
          gh repo fork project-mirai/mirai-repo-mirror --clone=false
          gh repo clone MesagistoBot/mirai-repo-mirror .github/mirai-repo-mirror

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Trim version tag
        id: get_version
        run: echo ::set-output name=VERSION::${TAG#v}
        env:
          TAG: ${{steps.get-latest-tag.outputs.tag}}

      - name: Render package.json
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .github/package.json.j2
          output_file: .github/package.json
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          TIME: ${{needs.prepare.outputs.time}}

      - name: PullRequest to Mirai-Repo
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_HOST: "github.com"
        run: |
          mv .github/package.json .github/mirai-repo-mirror/org/mesagisto/mirai-message-source/
          cd .github/mirai-repo-mirror
          git add org/mesagisto/mirai-message-source/package.json
          git commit -m "update mirai-message-source"
          git push origin master
          gh pr create --fill --repo project-mirai/mirai-repo-mirror
