name: release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Build
        run: bash build.sh

      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            packages/*.jar
            LICENSE
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Publish to MavenCentral
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}
        run: |
          chmod +x gradlew
          ./gradlew clean checkMavenCentralPublication
          ./gradlew build publish
          ./gradlew closeAndReleaseRepository

      - name: Clone Mirai-Repo
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_HOST: "github.com"
        run: |
          git config --global user.name "MesagistoBot"
          git config --global user.email "bot@mesagisto.org"
          gh auth setup-git
          gh repo delete MesagistoBot/mirai-repo-mirror --confirm
          gh repo fork project-mirai/mirai-repo-mirror --clone=false
          gh repo clone MesagistoBot/mirai-repo-mirror .github/mirai-repo-mirror

      - name: Get the version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Render package.json
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: .github/package.json.j2
          output_file: .github/package.json
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: PullRequest to Mirai-Repo
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_HOST: "github.com"
        run: |
          mv .github/package.json .github/mirai-repo-mirror/org/mesagisto/mirai-message-source/
          cd .github/mirai-repo-mirror
          git add org/mesagisto/mirai-message-source/package.json
          git commit -m "update mirai-message-source"
          git push origin master
          gh pr create --fill --repo project-mirai/mirai-repo-mirror

      - name: What's wrong with the AliMavenMirror
        run: |
          wget --tries=100 --retry-on-http-error=404 --wait=15 https://maven.aliyun.com/repository/public/org/mesagisto/mirai-message-source/${{ steps.get_version.outputs.VERSION }}/mirai-message-source-${{ steps.get_version.outputs.VERSION }}.mirai2.jar
